### ISSUE TITLE
[BUG] `s3cmd sync` fails with backtrace. ETag missing from response

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#598]
**Describe the bug** A clear and concise description of what the bug is.

`s3cmd sync` command fails due to ETag missing from response by s3gw.

**To Reproduce** Steps to reproduce the behavior:

Run `s3cmd sync` against the s3gw, if necessary multiple times with an empty directory to sync to and a bucket containing objects.
This command is supposed to sync the contents of a directory tree with an S3 bucket, but fails when syncing objects back from S3 to the directory.

s3cmd output:
```

#8 5.399 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#8 5.399     An unexpected error has occurred.
#8 5.399   Please try reproducing the error using
#8 5.399   the latest s3cmd code from the git master
#8 5.399   branch found at:
#8 5.399     https://github.com/s3tools/s3cmd
#8 5.399   and have a look at the known issues list:
#8 5.399     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
#8 5.399   If the error persists, please report the
#8 5.399   following lines (removing any private
#8 5.399   info as necessary) to:
#8 5.399    s3tools-bugs@lists.sourceforge.net
#8 5.399 
#8 5.399 
#8 5.399 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#8 5.399 
#8 5.399 Invoked as: /usr/bin/s3cmd -c /srv/ceph/s3cfg sync s3://s3gw-cache ./ceph/build.ccache
#8 5.399 Problem: <class 'KeyError: 'etag'
#8 5.399 S3cmd:   2.2.0
#8 5.399 python:   3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
#8 5.399 environment LANG=NOTSET
#8 5.399 
#8 5.399 Traceback (most recent call last):
#8 5.399   File "/usr/bin/s3cmd", line 3209, in <module>
#8 5.399     rc = main()
#8 5.399   File "/usr/bin/s3cmd", line 3106, in main
#8 5.399     rc = cmd_func(args)
#8 5.399   File "/usr/bin/s3cmd", line 1967, in cmd_sync
#8 5.399     return cmd_sync_remote2local(args)
#8 5.399   File "/usr/bin/s3cmd", line 1247, in cmd_sync_remote2local
#8 5.399     remote_list, src_exclude_list, remote_total_size = fetch_remote_list(fetch_source_args, recursive = True, require_attribs = True)
#8 5.399   File "/usr/lib/python3.6/site-packages/S3/FileLists.py", line 470, in fetch_remote_list
#8 5.399     objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
#8 5.399   File "/usr/lib/python3.6/site-packages/S3/FileLists.py", line 442, in _get_filelist_remote
#8 5.399     _get_remote_attribs(S3Uri(object_uri_str), rem_list[key])
#8 5.399   File "/usr/lib/python3.6/site-packages/S3/FileLists.py", line 374, in _get_remote_attribs
#8 5.399     'md5': response['headers']['etag'].strip('"\''),
#8 5.399 KeyError: 'etag'
#8 5.399 
#8 5.399 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#8 5.399     An unexpected error has occurred.
#8 5.399   Please try reproducing the error using
#8 5.399   the latest s3cmd code from the git master
#8 5.399   branch found at:
#8 5.399     https://github.com/s3tools/s3cmd
#8 5.399   and have a look at the known issues list:
#8 5.399     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
#8 5.399   If the error persists, please report the
#8 5.399   above lines (removing any private
#8 5.399   info as necessary) to:
#8 5.399    s3tools-bugs@lists.sourceforge.net
#8 5.399 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

[s3gw-logs.log](https://github.com/aquarist-labs/s3gw/files/11848933/s3gw-logs.log)

**Versions:**
s3gw v0.17.0
s3cmd 2.2.0

**Comment by jhmarina** [comment]
This may be related to #662

**Comment by 0xavi0** [comment]
I can't reproduce the issue.
I think the problem was objects listing which was changed after this issue was raised.

```bash
s3cmd -c ~/s3cmd.conf sync s3://test ./
download: 's3://test/test-obj' -> './test-obj'  [1 of 3]
 204 of 204   100% in    0s     4.21 KB/s  done
download: 's3://test/test-obj2' -> './test-obj2'  [2 of 3]
 20480 of 20480   100% in    0s   413.21 KB/s  done
download: 's3://test/test-obj3' -> './test-obj3'  [3 of 3]
 21694 of 21694   100% in    0s   492.40 KB/s  done
Done. Downloaded 42378 bytes in 1.0 seconds, 41.38 KB/s.
```
