### ISSUE TITLE
[BUG] `s3cmd get` fails because multipart objects are missing etag in response header when downloaded

### ISSUE THREAD

**Issue by tserong** [s3gw-tech/s3gw#658]
**Describe the bug**

If I `s3cmd put` an object using multipart upload, then later `s3cmd get` the object, the get will fail:

```
> echo test | s3cmd put - s3://foo/test-multipart
upload: '<stdin>' -> 's3://foo/test-multipart'  [part 1 of -, 5B] [1 of 1]
 5 of 5   100% in    0s   285.00 B/s  done

> > s3cmd -c .s3cfg-test get s3://foo/test-multipart /tmp/test

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /home/tserong/.local/bin/s3cmd -c .s3cfg-test get s3://foo/test-multipart /tmp/test
Problem: <class 'KeyError: 'etag'
S3cmd:   2.3.0
python:   3.11.4 (main, Jun 28 2023, 19:51:46) [GCC]
environment LANG=en_US.utf8

Traceback (most recent call last):
  File "/home/tserong/.local/bin/s3cmd", line 3286, in <module>
    rc = main()
         ^^^^^^
  File "/home/tserong/.local/bin/s3cmd", line 3183, in main
    rc = cmd_func(args)
         ^^^^^^^^^^^^^^
  File "/home/tserong/.local/bin/s3cmd", line 538, in cmd_object_get
    remote_list, exclude_list, remote_total_size = fetch_remote_list(
                                                   ^^^^^^^^^^^^^^^^^^
  File "/home/tserong/.local/lib/python3.11/site-packages/S3/FileLists.py", line 508, in fetch_remote_list
    _get_remote_attribs(uri, remote_item)
  File "/home/tserong/.local/lib/python3.11/site-packages/S3/FileLists.py", line 379, in _get_remote_attribs
    'md5': response['headers']['etag'].strip('"\''),
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'etag'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

For some reason, objects uploaded via multipart upload are lacking an etag in their HTTP response headers, whereas non-multipart uploads _do_ have an etag in their HTTP response headers when subsequently downloaded.

**To Reproduce**

1. Upload a non-multipart object (e.g. `s3cmd put test.txt s3://foo/test-file`)
2. Upload a multipart object (e.g.: `echo test | s3cmd -c put - s3://foo/test-multipart`)
3. Try to get the non-multipart object (`s3cmd get s3://foo/test-file /tmp/test`). This will work just fine.
4. Try to get the multipart object (`s3cmd get s3://foo/test-multipart /tmp/test`). This will fail as above.

**Expected behavior**

The download should succeed.

**Additional context**

The etags _do_ exist in the bucket XML output:

```
> curl http://127.0.0.1:7480/foo/ -s|xml_pp
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>foo</Name>
  <Prefix></Prefix>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>test-file</Key>
    <LastModified>2023-08-07T06:30:46.953Z</LastModified>
    <ETag>&quot;d8e8fca2dc0f896fd7cb4cb0031ba249&quot;</ETag>
    <Size>5</Size>
    <StorageClass>STANDARD</StorageClass>
    <Owner>
      <ID></ID>
      <DisplayName></DisplayName>
    </Owner>
    <Type>Normal</Type>
  </Contents>
  <Contents>
    <Key>test-multipart</Key>
    <LastModified>2023-08-07T06:31:23.061Z</LastModified>
    <ETag>&quot;d41d8cd98f00b204e9800998ecf8427e-1&quot;</ETag>
    <Size>5</Size>
    <StorageClass>STANDARD</StorageClass>
    <Owner>
      <ID></ID>
      <DisplayName></DisplayName>
    </Owner>
    <Type>Normal</Type>
  </Contents>
  <Marker></Marker>
</ListBucketResult>
```

The etag response header is present for the object that was uploaded _not_ using multipart:

```
> curl -D - http://127.0.0.1:7480/foo/test-file -o /dev/null -s
HTTP/1.1 200 OK
Content-Length: 5
Accept-Ranges: bytes
Last-Modified: Mon, 07 Aug 2023 06:30:46 GMT
x-amz-version-id: c26CbPbqVpyEx96E6v.lG.ttrPirhil
x-rgw-object-type: Normal
ETag: "d8e8fca2dc0f896fd7cb4cb0031ba249"
x-amz-meta-s3cmd-attrs: atime:1691389823/ctime:1691389823/gid:100/gname:users/md5:d8e8fca2dc0f896fd7cb4cb0031ba249/mode:33188/mtime:1691389823/uid:1000/uname:tserong
Content-Type: text/plain
Date: Mon, 07 Aug 2023 06:45:01 GMT
Server: Ceph Object Gateway (reef)
Connection: Keep-Alive
```

...but it's not there for the object that was uploaded using multipart:

```
> curl -D - http://127.0.0.1:7480/foo/test-multipart -o /dev/null -s
HTTP/1.1 200 OK
Content-Length: 5
Accept-Ranges: bytes
Last-Modified: Mon, 07 Aug 2023 06:31:23 GMT
x-amz-version-id: yatIqlbl6T.n8gLdqqEXQmEiYlJamrv
x-rgw-object-type: Normal
x-amz-meta-s3cmd-attrs: gname:users/uname:tserong
Content-Type: binary/octet-stream; charset=UTF-8
Date: Mon, 07 Aug 2023 06:45:10 GMT
Server: Ceph Object Gateway (reef)
Connection: Keep-Alive
```

**Comment by jhmarina** [comment]
This may be a duplicate. @0xavi0 will look into it
